export const categories = [
  'Today',
  'Electronics',
  'Computers',
  'Phones',
  'Home',
  'Kitchen',
  'Fashion',
  'Sports',
  'Travel',
  'Office',
]

export const promoDeals = [
  {
    id: 'p1',
    title: 'Sony WH-1000XM5 Headphones',
    price: 148,
    thumbBg: '#e8eef5',
    url: 'https://www.amazon.com/s?k=Sony+WH-1000XM5+Headphones',
  },
  {
    id: 'p2',
    title: 'LG 55" OLED 4K TV',
    price: 799,
    thumbBg: '#f5ede8',
    url: 'https://www.bestbuy.com/site/searchpage.jsp?st=LG+55+OLED+4K+TV',
  },
  {
    id: 'p3',
    title: 'Samsung Galaxy Watch 8',
    price: 165,
    thumbBg: '#edf5ed',
    url: 'https://www.amazon.com/s?k=Samsung+Galaxy+Watch+8',
  },
  {
    id: 'p4',
    title: 'Acer Aspire 5 Laptop',
    price: 449,
    thumbBg: '#f0eef8',
    url: 'https://www.amazon.com/s?k=Acer+Aspire+5+Laptop',
  },
]

export const deals = [
  {
    id: 1,
    title: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    merchant: 'AMAZON',
    category: 'Electronics',
    originalPrice: 349.99,
    salePrice: 148.0,
    discountPct: 58,
    thumbBg: '#eef3f8',
    url: 'https://www.amazon.com/s?k=Sony+WH-1000XM5+Wireless+Noise+Cancelling+Headphones',
    isStudentPick: true,
  },
  {
    id: 2,
    title: 'LG 55" OLED evo C3 Series 4K UHD Smart TV',
    merchant: 'BEST BUY',
    category: 'Electronics',
    originalPrice: 1499.99,
    salePrice: 799.0,
    discountPct: 47,
    thumbBg: '#faf4ee',
    url: 'https://www.bestbuy.com/site/searchpage.jsp?st=LG+55+OLED+evo+C3+Series+4K+UHD+Smart+TV',
    isStudentPick: false,
  },
  {
    id: 3,
    title: 'Samsung Galaxy Watch 8 44mm Smartwatch',
    merchant: 'WOOT',
    category: 'Electronics',
    originalPrice: 289.99,
    salePrice: 165.0,
    discountPct: 43,
    thumbBg: '#eef6ee',
    url: 'https://electronics.woot.com/plus/smartwatches-and-wearables',
    isStudentPick: false,
  },
  {
    id: 4,
    title: 'DeWalt 20V Max Cordless Drill Driver Set w/ Battery',
    merchant: 'HOME DEPOT',
    category: 'Home',
    originalPrice: 199.99,
    salePrice: 78.0,
    discountPct: 61,
    thumbBg: '#f8eeee',
    url: 'https://www.homedepot.com/s/DeWalt%2020V%20Max%20Cordless%20Drill%20Driver%20Set',
    isStudentPick: false,
  },
  {
    id: 5,
    title: 'Acer Aspire 5 15.6" FHD Laptop 16GB RAM 512GB SSD',
    merchant: 'AMAZON',
    category: 'Computers',
    originalPrice: 699.99,
    salePrice: 449.0,
    discountPct: 35,
    thumbBg: '#f0eef8',
    url: 'https://www.amazon.com/s?k=Acer+Aspire+5+15.6+FHD+Laptop+16GB+RAM+512GB+SSD',
    isStudentPick: true,
  },
  {
    id: 6,
    title: 'Dyson V8 Cordless Vacuum Cleaner Certified Refurbished',
    merchant: 'WALMART',
    category: 'Home',
    originalPrice: 399.99,
    salePrice: 189.0,
    discountPct: 52,
    thumbBg: '#eef5f5',
    url: 'https://www.walmart.com/search?q=Dyson+V8+Cordless+Vacuum+Cleaner+Certified+Refurbished',
    isStudentPick: false,
  },
  {
    id: 7,
    title: 'Ninja Creami 7-in-1 Ice Cream Maker Machine',
    merchant: 'WOOT',
    category: 'Kitchen',
    originalPrice: 299.99,
    salePrice: 99.0,
    discountPct: 68,
    thumbBg: '#faf5ee',
    url: 'https://home.woot.com/plus/kitchen-appliances-and-more',
    isStudentPick: true,
  },
  {
    id: 8,
    title: 'Reolink 4K Outdoor Security Camera System w/ NVR',
    merchant: 'EBAY',
    category: 'Home',
    originalPrice: 219.99,
    salePrice: 129.0,
    discountPct: 41,
    thumbBg: '#f0eef8',
    url: 'https://www.ebay.com/sch/i.html?_nkw=Reolink+4K+Outdoor+Security+Camera+System+NVR',
    isStudentPick: false,
  },
  {
    id: 9,
    title: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker 6Qt',
    merchant: 'TARGET',
    category: 'Kitchen',
    originalPrice: 99.99,
    salePrice: 59.0,
    discountPct: 39,
    thumbBg: '#f5f5ee',
    url: 'https://www.target.com/s?searchTerm=Instant+Pot+Duo+7-in-1+Electric+Pressure+Cooker+6Qt',
    isStudentPick: true,
  },
  {
    id: 10,
    title: 'Bose QuietComfort 45 Bluetooth Wireless Headphones',
    merchant: 'AMAZON',
    category: 'Electronics',
    originalPrice: 299.99,
    salePrice: 134.0,
    discountPct: 55,
    thumbBg: '#eef3ee',
    url: 'https://www.amazon.com/s?k=Bose+QuietComfort+45+Bluetooth+Wireless+Headphones',
    isStudentPick: false,
  },
]

export const studentDeals = []    id: 'p4',
    title: 'Acer Aspire 5 Laptop',
    price: 449,
    thumbBg: '#f0eef8',
    url: '#',
  },
]

export const deals = [
  {
    id: 1,
    title: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    merchant: 'AMAZON',
    category: 'Electronics',
    originalPrice: 349.99,
    salePrice: 148.0,
    discountPct: 58,
    thumbBg: '#eef3f8',
    url: '#',
    isStudentPick: true,
  },
  {
    id: 2,
    title: 'LG 55" OLED evo C3 Series 4K UHD Smart TV',
    merchant: 'BEST BUY',
    category: 'Electronics',
    originalPrice: 1499.99,
    salePrice: 799.0,
    discountPct: 47,
    thumbBg: '#faf4ee',
    url: '#',
    isStudentPick: false,
  },
  {
    id: 3,
    title: 'Samsung Galaxy Watch 8 44mm Smartwatch',
    merchant: 'WOOT',
    category: 'Electronics',
    originalPrice: 289.99,
    salePrice: 165.0,
    discountPct: 43,
    thumbBg: '#eef6ee',
    url: '#',
    isStudentPick: false,
  },
  {
    id: 4,
    title: 'DeWalt 20V Max Cordless Drill Driver Set w/ Battery',
    merchant: 'HOME DEPOT',
    category: 'Home',
    originalPrice: 199.99,
    salePrice: 78.0,
    discountPct: 61,
    thumbBg: '#f8eeee',
    url: '#',
    isStudentPick: false,
  },
  {
    id: 5,
    title: 'Acer Aspire 5 15.6" FHD Laptop 16GB RAM 512GB SSD',
    merchant: 'AMAZON',
    category: 'Computers',
    originalPrice: 699.99,
    salePrice: 449.0,
    discountPct: 35,
    thumbBg: '#f0eef8',
    url: '#',
    isStudentPick: true,
  },
  {
    id: 6,
    title: 'Dyson V8 Cordless Vacuum Cleaner Certified Refurbished',
    merchant: 'WALMART',
    category: 'Home',
    originalPrice: 399.99,
    salePrice: 189.0,
    discountPct: 52,
    thumbBg: '#eef5f5',
    url: '#',
    isStudentPick: false,
  },
  {
    id: 7,
    title: 'Ninja Creami 7-in-1 Ice Cream Maker Machine',
    merchant: 'WOOT',
    category: 'Kitchen',
    originalPrice: 299.99,
    salePrice: 99.0,
    discountPct: 68,
    thumbBg: '#faf5ee',
    url: '#',
    isStudentPick: true,
  },
  {
    id: 8,
    title: 'Reolink 4K Outdoor Security Camera System w/ NVR',
    merchant: 'EBAY',
    category: 'Home',
    originalPrice: 219.99,
    salePrice: 129.0,
    discountPct: 41,
    thumbBg: '#f0eef8',
    url: '#',
    isStudentPick: false,
  },
  {
    id: 9,
    title: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker 6Qt',
    merchant: 'TARGET',
    category: 'Kitchen',
    originalPrice: 99.99,
    salePrice: 59.0,
    discountPct: 39,
    thumbBg: '#f5f5ee',
    url: '#',
    isStudentPick: true,
  },
  {
    id: 10,
    title: 'Bose QuietComfort 45 Bluetooth Wireless Headphones',
    merchant: 'AMAZON',
    category: 'Electronics',
    originalPrice: 299.99,
    salePrice: 134.0,
    discountPct: 55,
    thumbBg: '#eef3ee',
    url: '#',
    isStudentPick: false,
  },
]

export const studentDeals = [
  {
    id: 's1',
    brand: 'Spotify',
    offer: 'Premium for Students',
    price: '$5.99/mo',
    originalPrice: '$11.99/mo',
    color: '#1DB954',
    url: '#',
  },
  {
    id: 's2',
    brand: 'Amazon Prime',
    offer: 'Student — 6 months free',
    price: '$0',
    originalPrice: '$139/yr',
    color: '#FF9900',
    url: '#',
  },
  {
    id: 's3',
    brand: 'Apple Music',
    offer: 'Student Discount',
    price: '$5.99/mo',
    originalPrice: '$10.99/mo',
    color: '#FC3C44',
    url: '#',
  },
  {
    id: 's4',
    brand: 'Adobe CC',
    offer: 'Creative Cloud Student',
    price: '$19.99/mo',
    originalPrice: '$59.99/mo',
    color: '#FF0000',
    url: '#',
  },
  {
    id: 's5',
    brand: 'Microsoft 365',
    offer: 'Education — Free',
    price: '$0',
    originalPrice: '$99.99/yr',
    color: '#0078D4',
    url: '#',
  },
  {
    id: 's6',
    brand: 'Notion',
    offer: 'Plus Plan for Students',
    price: '$0',
    originalPrice: '$16/mo',
    color: '#000000',
    url: '#',
  },
]
