export const categories = [
  'Today',
  'Electronics',
  'Computers',
  'Phones',
  'Home',
  'Kitchen',
  'Fashion',
  'Sports',
  'Travel',
  'Toys',
  'Textbooks',
  'Software',
  'Dorm',
  'Office',
  'Beauty',
  'Automotive',
  'Tools',
  'Pets',
  'Food',
]

const amznImg = (asin) =>
  `https://images-na.ssl-images-amazon.com/images/P/${asin}.01._SL300_.jpg`

export const promoDeals = [
  {
    id: 'p1',
    title: 'Sony WH-1000XM5 Headphones',
    price: 148,
    image: amznImg('B09XS7JWHH'),
    thumbBg: '#e8eef5',
    merchant: 'AMAZON',
    url: 'https://www.amazon.com/dp/B09XS7JWHH',
    productUrl: 'https://www.amazon.com/dp/B09XS7JWHH',
  },
  {
    id: 'p2',
    title: 'LG 55" OLED 4K TV',
    price: 799,
    image: amznImg('B0BVX9MFR8'),
    thumbBg: '#f5ede8',
    merchant: 'BEST BUY',
    url: 'https://www.bestbuy.com/site/lg-55-class-c3-series-oled-4k-uhd-smart-webos-tv/6535933.p',
    productUrl:
      'https://www.bestbuy.com/site/lg-55-class-c3-series-oled-4k-uhd-smart-webos-tv/6535933.p',
  },
  {
    id: 'p3',
    title: 'Samsung Galaxy Watch 6 44mm Smartwatch',
    price: 169.99,
    image: amznImg('B0C6BGWB3M'),
    thumbBg: '#edf5ed',
    merchant: 'AMAZON',
    url: 'https://www.amazon.com/dp/B0C6BGWB3M',
    productUrl: 'https://www.amazon.com/dp/B0C6BGWB3M',
  },
  {
    id: 'p4',
    title: 'Acer Aspire 5 Laptop',
    price: 449,
    image: amznImg('B09NQXS8XJ'),
    thumbBg: '#f0eef8',
    merchant: 'AMAZON',
    url: 'https://www.amazon.com/dp/B09NQXS8XJ',
    productUrl: 'https://www.amazon.com/dp/B09NQXS8XJ',
  },
]

export const deals = [
  {
    id: 1,
    title: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    merchant: 'AMAZON',
    category: 'Electronics',
    originalPrice: 349.99,
    salePrice: 148.0,
    discountPct: 58,
    thumbBg: '#eef3f8',
    image: amznImg('B09XS7JWHH'),
    url: 'https://www.amazon.com/dp/B09XS7JWHH',
    productUrl: 'https://www.amazon.com/dp/B09XS7JWHH',
    isStudentPick: true,
  },
  {
    id: 2,
    title: 'LG 55" OLED evo C3 Series 4K UHD Smart TV',
    merchant: 'BEST BUY',
    category: 'Electronics',
    originalPrice: 1499.99,
    salePrice: 799.0,
    discountPct: 47,
    thumbBg: '#faf4ee',
    image: amznImg('B0BVX9MFR8'),
    url: 'https://www.bestbuy.com/site/lg-55-class-c3-series-oled-4k-uhd-smart-webos-tv/6535933.p',
    productUrl:
      'https://www.bestbuy.com/site/lg-55-class-c3-series-oled-4k-uhd-smart-webos-tv/6535933.p',
    isStudentPick: false,
  },
  {
    id: 3,
    title: 'Samsung Galaxy Watch 6 44mm Smartwatch',
    merchant: 'AMAZON',
    category: 'Electronics',
    originalPrice: 379.99,
    salePrice: 169.99,
    discountPct: 55,
    thumbBg: '#eef6ee',
    image: amznImg('B0C6BGWB3M'),
    url: 'https://www.amazon.com/dp/B0C6BGWB3M',
    productUrl: 'https://www.amazon.com/dp/B0C6BGWB3M',
    isStudentPick: false,
  },
  {
    id: 4,
    title: 'DEWALT 20V MAX Cordless Drill/Driver Kit',
    merchant: 'AMAZON',
    category: 'Tools',
    originalPrice: 199.99,
    salePrice: 78.0,
    discountPct: 61,
    thumbBg: '#f8eeee',
    image: amznImg('B00ET5VMTU'),
    url: 'https://www.amazon.com/dp/B00ET5VMTU',
    productUrl: 'https://www.amazon.com/dp/B00ET5VMTU',
    isStudentPick: false,
  },
  {
    id: 5,
    title: 'Acer Aspire 5 15.6" FHD Laptop 16GB RAM 512GB SSD',
    merchant: 'AMAZON',
    category: 'Computers',
    originalPrice: 699.99,
    salePrice: 449.0,
    discountPct: 35,
    thumbBg: '#f0eef8',
    image: amznImg('B09NQXS8XJ'),
    url: 'https://www.amazon.com/dp/B09NQXS8XJ',
    productUrl: 'https://www.amazon.com/dp/B09NQXS8XJ',
    isStudentPick: true,
  },
  {
    id: 6,
    title: 'Dyson V8 Origin+ Cordless Vacuum',
    merchant: 'WALMART',
    category: 'Home',
    originalPrice: 419.99,
    salePrice: 270.41,
    discountPct: 36,
    thumbBg: '#eef5f5',
    image: amznImg('B01HZXUT2S'),
    url: 'https://www.walmart.com/ip/728762765',
    productUrl: 'https://www.walmart.com/ip/728762765',
    isStudentPick: false,
  },
  {
    id: 7,
    title: 'Ninja Creami 7-in-1 Ice Cream & Frozen Treat Maker',
    merchant: 'AMAZON',
    category: 'Kitchen',
    originalPrice: 299.99,
    salePrice: 99.0,
    discountPct: 68,
    thumbBg: '#faf5ee',
    image: amznImg('B092DWFJWQ'),
    url: 'https://www.amazon.com/dp/B092DWFJWQ',
    productUrl: 'https://www.amazon.com/dp/B092DWFJWQ',
    isStudentPick: true,
  },
  {
    id: 8,
    title: 'Reolink 4K Outdoor Security Camera System w/ Night Vision',
    merchant: 'AMAZON',
    category: 'Home',
    originalPrice: 219.99,
    salePrice: 129.0,
    discountPct: 41,
    thumbBg: '#f0eef8',
    image: amznImg('B08BKVY4ZC'),
    url: 'https://www.amazon.com/dp/B08BKVY4ZC',
    productUrl: 'https://www.amazon.com/dp/B08BKVY4ZC',
    isStudentPick: false,
  },
  {
    id: 9,
    title: 'Instant Pot RIO 6qt 7-in-1 Electric Pressure Cooker',
    merchant: 'TARGET',
    category: 'Kitchen',
    originalPrice: 109.99,
    salePrice: 89.99,
    discountPct: 18,
    thumbBg: '#f5f5ee',
    image: amznImg('B00FLYWNYQ'),
    url: 'https://www.target.com/p/-/A-89077383',
    productUrl: 'https://www.target.com/p/-/A-89077383',
    isStudentPick: true,
  },
  {
    id: 10,
    title: 'Bose QuietComfort 45 Bluetooth Wireless Headphones',
    merchant: 'AMAZON',
    category: 'Electronics',
    originalPrice: 299.99,
    salePrice: 134.0,
    discountPct: 55,
    thumbBg: '#eef3ee',
    image: amznImg('B098FKXT8L'),
    url: 'https://www.amazon.com/dp/B098FKXT8L',
    productUrl: 'https://www.amazon.com/dp/B098FKXT8L',
    isStudentPick: false,
  },
]

export const studentDeals = [
  {
    id: 's1',
    brand: 'Spotify',
    offer: 'Premium for Students',
    price: '$5.99/mo',
    originalPrice: '$11.99/mo',
    color: '#1DB954',
    url: 'https://www.spotify.com/us/student/',
  },
  {
    id: 's2',
    brand: 'Amazon Prime',
    offer: 'Student — 6 months free',
    price: '$0',
    originalPrice: '$139/yr',
    color: '#FF9900',
    url: 'https://www.amazon.com/joinstudent',
  },
  {
    id: 's3',
    brand: 'Apple Music',
    offer: 'Student Discount',
    price: '$5.99/mo',
    originalPrice: '$10.99/mo',
    color: '#FC3C44',
    url: 'https://www.apple.com/shop/buy-music/membership/student',
  },
  {
    id: 's4',
    brand: 'Adobe CC',
    offer: 'Creative Cloud Student',
    price: '$19.99/mo',
    originalPrice: '$59.99/mo',
    color: '#FF0000',
    url: 'https://www.adobe.com/creativecloud/buy/students.html',
  },
  {
    id: 's5',
    brand: 'Microsoft 365',
    offer: 'Education — Free',
    price: '$0',
    originalPrice: '$99.99/yr',
    color: '#0078D4',
    url: 'https://www.microsoft.com/en-us/education/products/office',
  },
  {
    id: 's6',
    brand: 'Notion',
    offer: 'Plus Plan for Students',
    price: '$0',
    originalPrice: '$16/mo',
    color: '#000000',
    url: 'https://www.notion.so/product/notion-for-education',
  },
]
