export const categories = [
  'Today',
  'Electronics',
  'Computers',
  'Phones',
  'Home',
  'Kitchen',
  'Fashion',
  'Sports',
  'Travel',
  'Office',
]

export const promoDeals = [
  {
    id: 'p1',
    title: 'Sony WH-1000XM5 Headphones',
    price: 148,
    thumbBg: '#e8eef5',
    url: 'https://www.amazon.com/s?k=Sony+WH-1000XM5+Headphones',
    image: 'https://dummyimage.com/300x180/e8eef5/111111&text=Sony+WH-1000XM5',
  },
  {
    id: 'p2',
    title: 'LG 55" OLED 4K TV',
    price: 799,
    thumbBg: '#f5ede8',
    url: 'https://www.bestbuy.com/site/searchpage.jsp?st=LG+55+OLED+4K+TV',
    image: 'https://dummyimage.com/300x180/f5ede8/111111&text=LG+55%22+OLED+TV',
  },
  {
    id: 'p3',
    title: 'Samsung Galaxy Watch 8',
    price: 165,
    thumbBg: '#edf5ed',
    url: 'https://www.amazon.com/s?k=Samsung+Galaxy+Watch+8',
    image: 'https://dummyimage.com/300x180/edf5ed/111111&text=Galaxy+Watch+8',
  },
  {
    id: 'p4',
    title: 'Acer Aspire 5 Laptop',
    price: 449,
    thumbBg: '#f0eef8',
    url: 'https://www.amazon.com/s?k=Acer+Aspire+5+Laptop',
    image: 'https://dummyimage.com/300x180/f0eef8/111111&text=Acer+Aspire+5',
  },
]

export const deals = [
  {
    id: 1,
    title: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    merchant: 'AMAZON',
    category: 'Electronics',
    originalPrice: 349.99,
    salePrice: 148.0,
    discountPct: 58,
    thumbBg: '#eef3f8',
    url: 'https://www.amazon.com/s?k=Sony+WH-1000XM5+Wireless+Noise+Cancelling+Headphones',
    image: 'https://dummyimage.com/420x220/eef3f8/111111&text=Sony+WH-1000XM5',
    isStudentPick: true,
  },
  {
    id: 2,
    title: 'LG 55" OLED evo C3 Series 4K UHD Smart TV',
    merchant: 'BEST BUY',
    category: 'Electronics',
    originalPrice: 1499.99,
    salePrice: 799.0,
    discountPct: 47,
    thumbBg: '#faf4ee',
    url: 'https://www.bestbuy.com/site/searchpage.jsp?st=LG+55+OLED+evo+C3+Series+4K+UHD+Smart+TV',
    image: 'https://dummyimage.com/420x220/faf4ee/111111&text=LG+55%22+OLED+C3',
    isStudentPick: false,
  },
  {
    id: 3,
    title: 'Samsung Galaxy Watch 8 44mm Smartwatch',
    merchant: 'WOOT',
    category: 'Electronics',
    originalPrice: 289.99,
    salePrice: 165.0,
    discountPct: 43,
    thumbBg: '#eef6ee',
    url: 'https://electronics.woot.com/plus/smartwatches-and-wearables',
    image: 'https://dummyimage.com/420x220/eef6ee/111111&text=Galaxy+Watch+8',
    isStudentPick: false,
  },
  {
    id: 4,
    title: 'DeWalt 20V Max Cordless Drill Driver Set w/ Battery',
    merchant: 'HOME DEPOT',
    category: 'Home',
    originalPrice: 199.99,
    salePrice: 78.0,
    discountPct: 61,
    thumbBg: '#f8eeee',
    url: 'https://www.homedepot.com/s/DeWalt%2020V%20Max%20Cordless%20Drill%20Driver%20Set',
    image: 'https://dummyimage.com/420x220/f8eeee/111111&text=DeWalt+20V+Drill',
    isStudentPick: false,
  },
  {
    id: 5,
    title: 'Acer Aspire 5 15.6" FHD Laptop 16GB RAM 512GB SSD',
    merchant: 'AMAZON',
    category: 'Computers',
    originalPrice: 699.99,
    salePrice: 449.0,
    discountPct: 35,
    thumbBg: '#f0eef8',
    url: 'https://www.amazon.com/s?k=Acer+Aspire+5+15.6+FHD+Laptop+16GB+RAM+512GB+SSD',
    image: 'https://dummyimage.com/420x220/f0eef8/111111&text=Acer+Aspire+5',
    isStudentPick: true,
  },
  {
    id: 6,
    title: 'Dyson V8 Cordless Vacuum Cleaner Certified Refurbished',
    merchant: 'WALMART',
    category: 'Home',
    originalPrice: 399.99,
    salePrice: 189.0,
    discountPct: 52,
    thumbBg: '#eef5f5',
    url: 'https://www.walmart.com/search?q=Dyson+V8+Cordless+Vacuum+Cleaner+Certified+Refurbished',
    image: 'https://dummyimage.com/420x220/eef5f5/111111&text=Dyson+V8',
    isStudentPick: false,
  },
  {
    id: 7,
    title: 'Ninja Creami 7-in-1 Ice Cream Maker Machine',
    merchant: 'WOOT',
    category: 'Kitchen',
    originalPrice: 299.99,
    salePrice: 99.0,
    discountPct: 68,
    thumbBg: '#faf5ee',
    url: 'https://home.woot.com/plus/kitchen-appliances-and-more',
    image: 'https://dummyimage.com/420x220/faf5ee/111111&text=Ninja+Creami',
    isStudentPick: true,
  },
  {
    id: 8,
    title: 'Reolink 4K Outdoor Security Camera System w/ NVR',
    merchant: 'EBAY',
    category: 'Home',
    originalPrice: 219.99,
    salePrice: 129.0,
    discountPct: 41,
    thumbBg: '#f0eef8',
    url: 'https://www.ebay.com/sch/i.html?_nkw=Reolink+4K+Outdoor+Security+Camera+System+NVR',
    image: 'https://dummyimage.com/420x220/f0eef8/111111&text=Reolink+4K+Camera',
    isStudentPick: false,
  },
  {
    id: 9,
    title: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker 6Qt',
    merchant: 'TARGET',
    category: 'Kitchen',
    originalPrice: 99.99,
    salePrice: 59.0,
    discountPct: 39,
    thumbBg: '#f5f5ee',
    url: 'https://www.target.com/s?searchTerm=Instant+Pot+Duo+7-in-1+Electric+Pressure+Cooker+6Qt',
    image: 'https://dummyimage.com/420x220/f5f5ee/111111&text=Instant+Pot+Duo',
    isStudentPick: true,
  },
  {
    id: 10,
    title: 'Bose QuietComfort 45 Bluetooth Wireless Headphones',
    merchant: 'AMAZON',
    category: 'Electronics',
    originalPrice: 299.99,
    salePrice: 134.0,
    discountPct: 55,
    thumbBg: '#eef3ee',
    url: 'https://www.amazon.com/s?k=Bose+QuietComfort+45+Bluetooth+Wireless+Headphones',
    image: 'https://dummyimage.com/420x220/eef3ee/111111&text=Bose+QC45',
    isStudentPick: false,
  },
]

export const studentDeals = []
